# project:
#   type: website
resources:
  - CNAME

website:
  title: "Dmitriy Popov-Velasco"
  #title: "dpv-site"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - href: about.qmd
  #       text: About
  favicon: favicon.ico
  navbar:
    pinned: true

    left:
      - text: "About"
        href: index.html
      - text: "Blogs"
        href: posts.html
      - text: "Projects"
        file: projects.html
      - text: Notes
        file: notes.html

    right:
      - icon: linkedin 
        href: https://www.linkedin.com/in/dapvelasco
      - icon: envelope
        aria-label: email
        href: "mailto:dpopovvelasco@gmail.com"
      - icon: github
        href: https://github.com/dapopov-st

  search: 
    location: navbar
    type: textbox
  page-footer: 
    center: |
      <span class="faux-block">&#169; 2024 Dmitriy Popov-Velasco CC BY-SA 4.0</span>
    

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true
  cache: true
  cache-dir: .quarto
  log: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true


    # format:
#   html:
#     theme: cosmo
#     #css: styles.css
#     toc: true
files:
  - posts.qmd
  - projects.qmd
  - notes.qmd
  - index.qmd


# html: 
#   includes:
#     in_header: favicon.html