project:
  type: website
resources:
  - CNAME

website:
  title: "Dmitriy Popov-Velasco"
  #title: "dpv-site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

  navbar:
    title: false
    background: dark
    pinned: false
    collapse: false
    left:
    - text: "Blogs"
      href: blog/blogs.qmd
    - text: "Projects"
      file: projects/projects.qmd
    - text: Notes
      file: notes/notes.qmd
    - text: Contact Me
      href: dpopovvelasco@gmail.com
      target: _blank

# format:
#   html:
#     theme: cosmo
#     css: styles.css
#     toc: true

format:
  html:
    reference-location: document
    theme: 
      dark: [solar, custom.scss]
      light: [flatly, custom-light.scss]
    css:
      - styles.css
    toc: true
    # syntax-definitions: 
    # - fomo.xml

execute: 
  freeze: auto