project:
  type: website
resources:
  - CNAME

website:
  title: "Dmitriy Popov-Velasco"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

# format:
#   html:
#     theme: cosmo
#     css: styles.css
#     toc: true

format:
  html:
    reference-location: document
    theme: 
      dark: [solar, custom.scss]
      light: [flatly, custom-light.scss]
    css:
      - styles.css
    toc: true
    syntax-definitions: 
    - fomo.xml

execute: 
  freeze: auto