project:
  type: website
resources:
  - CNAME

website:
  title: "Dmitriy Popov-Velasco"
  #title: "dpv-site"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - href: about.qmd
  #       text: About

  navbar:
    title: false
    background: dark
    pinned: false
    collapse: false
    left:
    - text: "About"
      href: index.html
    - text: "Blogs"
      href: posts.html
    - text: "Projects"
      file: projects.html
    - text: Notes
      file: notes.html
    - text: Contact
      href: contact.html
      target: _blank

# format:
#   html:
#     theme: cosmo
#     #css: styles.css
#     toc: true
files:
  - posts.qmd
  - projects.qmd
  - notes.qmd
  - index.qmd
  #- about.qmd
# format:
#   html:
#     reference-location: document
#     theme: 
#       dark: [solar, custom.scss]
#       light: [flatly, custom-light.scss]
#     css:
#       - styles.css
#     toc: true
#     # syntax-definitions: 
#     # - fomo.xml
format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
execute: 
  freeze: auto